### ISSUE TITLE
Python query results issue

### ISSUE THREAD

**Issue by duke-arioch** [weaviate/weaviate-python-client#415]
Hi I am getting the following instead of a dict:

<bound method GetBuilder.do of <weaviate.gql.get.GetBuilder object at 0x00000180DAE07A60>>

when I execute a query from the below using a string value for question:
```
nearText = {"concepts": [question]}
fragments = (client.query.get("Fragment", ["page_content"]).with_near_text(nearText).with_limit(3).do)
```

Using weaviate-client 3.22.1

Am I doing something wrong?

**Comment by duke-arioch** [comment]
this same query works fine if i use:

`
client.query.raw(client.query.get("Fragment", ["page_content"]).with_near_text(nearText).with_limit(3).build())
`

**Comment by dirkkul** [comment]
can you try this:
```
fragments = client.query.get("Fragment", ["page_content"]).with_near_text(nearText).with_limit(3).do()
```

**Comment by duke-arioch** [comment]
```
builder = client.query.get("Fragment", ["page_content"]).with_near_text("my question").with_limit(3)
result = builder.do()
```

results in the following from filter.py
`TypeError: NearText filter is expected to be type dict but is <class 'str'>
`

**Comment by tsmith023** [comment]
@duke-arioch, your initial problem was that your builder sequence was not being invoked properly since you were missing the `()` on your `do` method, _i.e._ `.with_limit(3).do` (incorrect) instead of `.with_limit(3).do()` (correct).

Now your second issue is that the argument to the `.with_near_text` method must be a dictionary rather than a string. This dictionary has multiple options that you can provide to it with the documentation going into detail on how to do it with the Python client [here](https://weaviate.io/developers/weaviate/api/graphql/search-operators#neartext).

Finally, these types of implementation and usage questions are better posted on the community slack channel, which you can access [here](https://weaviate.io/slack). I will close this as completed since it is a problem of usage, if you have further questions then please hop onto the slack channel and we can help you there! 😁
