### ISSUE TITLE
query escape for bm25 query

### ISSUE THREAD

**Issue by junfengye** [weaviate/weaviate-python-client#444]
query contains `\\\` or `"""` or `\r` failed with bm25 query, error message:

```
 Error during query: [{'locations': [{'column': 184, 'line': 1}], 'message': 'Syntax Error GraphQL request (1:184) Unterminated string.\n\n1: {Get{Vector_index_c5d5eb82_6405_4809_991c_37a2d792e224_Node(limit: 3 bm25:{query: "\\\\\\", properties: ["text"]}){text doc_id dataset_id document_id _additional {explainScore score }}}}\n ^\n', 'path': None}]
```

**Comment by tsmith023** [comment]
Hi @junfengye, these types of errors are due to the way the underlying GraphQL protocol handles unescaped string characters. Can you confirm which version of the Python client you are using?

**Comment by junfengye** [comment]
> Hi @junfengye, these types of errors are due to the way the underlying GraphQL protocol handles unescaped string characters. Can you confirm which version of the Python client you are using?

I upgrade to v3.23.1, `\\\` still not working, because you just handle the `"` case...

**Comment by tsmith023** [comment]
I would say that this unique use-case is so specific that it does not warrant a highly detailed regex pattern to find out all the unescaped backslashes within a string that not only preserves backwards compatibility but also does not return false positives & negatives

If you can come up with such a regex then I encourage you to open a PR to contribute to the library 😁 Otherwise, I think you should escape your backslashes in this narrow use-case before passing them to the Python client
